services:
  - type: web
    name: yourtube-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: yourtube-frontend
    runtime: node
    rootDir: yourtube
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
